// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWev9Ox1Zh6lcUAt7Q34ZC6vQDHUT6G8',
    appId: '1:861994739059:web:a40eeaf7e356cb7c2e9106',
    messagingSenderId: '861994739059',
    projectId: 'doppelmail-esoft6sa',
    authDomain: 'doppelmail-esoft6sa.firebaseapp.com',
    storageBucket: 'doppelmail-esoft6sa.appspot.com',
    measurementId: 'G-CW145LWE7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQrxlrq1Ns0muJkU1EkialKBW8nKJ4fA',
    appId: '1:861994739059:android:08654ab247ea71332e9106',
    messagingSenderId: '861994739059',
    projectId: 'doppelmail-esoft6sa',
    storageBucket: 'doppelmail-esoft6sa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbRJqEc-I5CXAMX2Ft-ON05aBpGQnwo8M',
    appId: '1:861994739059:ios:60d8d7f3f3bb05902e9106',
    messagingSenderId: '861994739059',
    projectId: 'doppelmail-esoft6sa',
    storageBucket: 'doppelmail-esoft6sa.appspot.com',
    iosBundleId: 'com.example.cloneGmail',
  );
}
